### PR TITLE
Support cloud api v3

### PR DESCRIPTION
**Pull request by aajdinov**
Added support for Cloud API v3.
Addressed some of the code styling issues reported by rubocop.

### CODE REVIEW

**Comment by edevenport** [comment]
Hello @plribeiro3000 - this PR includes support for the ProfitBricks Cloud API version 3. This provides support for volume availability zones and NAT to be enabled on NICs. I also asked @aajdinov to address some of the rubocop issues which was included as well.

If everything looks good, then we can tag a major release.

**Comment by edevenport** [comment]
@plribeiro3000 - Are you ok with me merging this PR? The Cloud API v3 updates are minimal - API URL update, volume availability zones, and a NAT parameters on NICs. Most of the changes are rubocop related.

**Comment by plribeiro3000** [comment]
@edevenport Sure. If you are ok then do it. Don´t let me block it. =)

**Comment by plribeiro3000** [comment]
I just appear occasionally when i see something that we need to fix. If i don´t comment nor anything go ahead. I can always comment later and we can undo something if it is really bad. 👍

**Pull request merged**
