### PR TITLE
Use relative paths, reduce requires and use path accordingly namespaces

### PR DESCRIPTION
**Pull request by plribeiro3000**
relates to fog/fog#3430

This is a huge diff but sounds like it did the trick. I'm opening this as a start point so we can discuss about it and find the best approach to tackle it.

The changes are:

* Use `autoload` so extra files only get loaded when needed
* Use relative paths
* Move the logic in the `fog/profitbricks/core` file to the `fog/profitbricks` since this is the only one bundler will load automatically.
* Remove some unnecessary requires in the models
* Move some files so the path will match the namespace

### CODE REVIEW

**Comment by edevenport** [comment]
@plribeiro3000 - Excellent, thank you!

This is quite a bit to go through. I have been traveling recently, but will attempt to look through it later this week and confirm it passes live tests against the platform. One thing I noticed is that you used "profit_bricks" for some of the directory and filenames. Could these be adjusted to simply, "profitbricks"?

**Comment by plribeiro3000** [comment]
@edevenport Yeah. Let me take a look at it first. It might have some issues like with `fog-brightbox`.
I've moved the files just to be more like the namespace but we can actually dump that.
This week will be a bit busy but this should be updated next wiki. =)

**Comment by edevenport** [comment]
@plribeiro3000 Ah, you are absolutely right about the namespace. I was too focused on the brand label when I should be focused on the namespace and code clarity. Let's return the filenames "profitbricks" and I'll find some time to go through and adjust the class names to "Profitbricks..." instead of "ProfitBricks..." which is probably a better representation and more clear to others.

**Comment by plribeiro3000** [comment]
@edevenport Sure. no problem. As soon as a i find sometime i will work on this. =)

**Comment by plribeiro3000** [comment]
@edevenport Can you take another look at this?

When you merge this i will send another PR to work on the naming (from `ProfitBricks` to `Profitbricks`).

**Comment by plribeiro3000** [comment]
@edevenport ping. :sweat: 

This is the only missing piece to close the fog regression issue.

**Comment by edevenport** [comment]
@plribeiro3000 Sorry! I've been traveling in Europe and trying to complete a few other high priority projects. I'll try to review this week and merge the PR.

**Comment by plribeiro3000** [comment]
@edevenport No problem man. Thank you!

**Comment by edevenport** [comment]
@plribeiro3000 I was manually testing the branch before merging the PR and ran into a issue. It seems to be loading the parsers from the wrong directory:

irb(main):004:0> service.datacenters.all
LoadError: cannot load such file -- /usr/local/share/gems/gems/fog-profitbricks-0.0.3/lib/fog/parsers/profit_bricks/get_all_data_centers
	from /usr/local/share/gems/gems/fog-profitbricks-0.0.3/lib/fog/compute/profit_bricks/requests/get_all_data_centers.rb:14:in `get_all_data_centers'
	from /usr/local/share/gems/gems/fog-profitbricks-0.0.3/lib/fog/compute/profit_bricks/models/datacenters.rb:10:in `all'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'

The unit tests in place are for the request methods, but not the parser or models. This is why Travis CI passes despite the issue.

**Comment by edevenport** [comment]
@plribeiro3000 I spent some time today reviewing the unit tests. The hope was that perhaps introducing some model tests would expose the above described error. However, this is not the case as some of the request tests do indeed use models and they still pass. The issue lies in the mock data which is not using the parser. A live test would have exposed the problem.

ProfitBricks has released a REST API and I would like to adjust the requests to use this API instead of their legacy SOAP API. However, we will need to get the restructuring completed before I start on that. I have some time to focus on fog-profitbricks, so let me know what you need.

**Comment by plribeiro3000** [comment]
@edevenport I will fix the parser stuff now and ping you again.

**Comment by plribeiro3000** [comment]
@edevenport Just fixed it. It was my mistake. After i reworked the code i forgot to fix the path of the parsers.

Thanks you for your time!

**Comment by plribeiro3000** [comment]
@edevenport Can you make a new release with those changes please?

**Comment by edevenport** [comment]
@plribeiro3000 - Done. Thank you for the PR.

**Comment by plribeiro3000** [comment]
@edevenport Sure. no worries. =)

**Pull request merged**
